export const selectors = {
  appRoot: "#root",
  composerInput: '[data-testid="session-composer-input"]',
  composerStorageKey: "data-composer-storage-key",
  composerSessionQueueKey: "data-composer-session-queue-key",
  composerSend: '[data-testid="session-composer-send-button"]',
  composerTargetHeading: '[data-testid="composer-entry-target-heading"]',
  leftSidebar: '[data-testid="session-left-sidebar"]',
  operationalError: '[data-testid="session-operational-error"]',
  rendererRecovery: '[data-testid="renderer-error-recovery"]',
  implicitSkillConfirmRun: '[data-testid="implicit-skill-confirm-run"]',
  runIndicator: '[data-testid="session-run-indicator"]',
  runtimeReadiness: '[data-testid="sidebar-runtime-readiness-status"]',
  serverStatus: '[data-testid="sidebar-veslo-server-status"]',
  sessionCapabilitiesPanel: '[data-testid="session-capabilities-panel"]',
  sessionCapabilitiesSkills: '[data-testid="session-capabilities-skills"]',
  sessionCapabilitiesSkillsContent: '#session-capabilities-skills-content',
  sessionCenterPane: '[data-testid="session-center-pane"]',
  assistantMessage: '[data-message-role="assistant"]',
  projectHeading: 'button[data-project-collapse-toggle] span.truncate, button span.truncate',
  projectNewSession: '[data-testid="sidebar-project-new-session"]',
};
