import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const docsRoot = new URL("../../../docs/", import.meta.url)

function readDoc(path: string): string {
  return readFileSync(new URL(path, docsRoot), "utf8")
}

test("canonical docs preserve the managed-AI ownership and runtime order contract", () => {
  const admin = readDoc("admin-managed-ai-access.md")
  const session = readDoc("features/session-runtime.md")
  const billing = readDoc("features/organization-billing.md")
  const onboarding = readDoc("features/onboarding-and-auth.md")
  const deployments = readDoc("dev/cloud-deployments.md")
  const state = readDoc("dev/state-and-config-reference.md")
  const appMap = readDoc("dev/app-map.md")
  const settings = readDoc("features/settings-and-preferences.md")
  const denReadme = readFileSync(new URL("../../den/README.md", import.meta.url), "utf8")
  const index = readDoc("INDEX.md")
  const canonicalManagedAiDocs = [admin, session, billing, onboarding, deployments, state, appMap, settings, denReadme].join("\n")

  assert.match(admin, /session.*billing entitlement.*user enablement.*global model.*credential/is)
  assert.match(admin, /no custom per-user or per-organization Managed-AI model policies/i)
  assert.match(admin, /Credential selection and rotation are separate from model selection/i)
  assert.match(
    admin,
    /Standalone AI Gateway is authoritative for inference, AI-access assignments,\s*the single global active model, credentials, and usage/i,
  )
  assert.doesNotMatch(admin, /DEN admin and standalone AI Gateway admin `Credentials` pages/i)
  assert.match(admin, /inference.*positive DEN organization entitlement.*missing AI-access record.*enabled/is)
  assert.match(admin, /self-access.*authenticated session.*without.*billing entitlement/is)
  assert.match(admin, /organization-qualified admin GET.*membership.*authorization.*without.*billing entitlement/is)
  assert.match(admin, /explicitly disabled.*preserved/i)
  assert.match(admin, /global platform model policy.*credential capability/is)
  assert.match(admin, /exactly one global active model.*exclusive runtime/i)
  assert.match(admin, /user-supplied model.*cannot.*switch/i)
  assert.match(admin, /self-access.*selectableModels.*empty/is)
  assert.match(admin, /historical per-user.*provider.*default_model.*allowed_models_json.*not.*runtime authority/is)
  assert.match(admin, /rejects.*provider.*credential.*model.*routing/is)
  assert.match(admin, /member modal.*AI Access.*platform admin/is)
  assert.match(admin, /AI Infrastructure.*models.*credentials/is)
  assert.match(admin, /DEN.*`\/admin`.*redirect.*standalone AI Gateway/is)
  assert.match(admin, /direct.*DEN.*enable.*resolver.*fails closed/is)

  assert.match(session, /DEN provider inference remains retired/i)
  assert.match(session, /denInferenceMode: "retired"/i)
  assert.match(session, /denInferenceMode: "legacy_rollback"/i)
  assert.match(session, /no operator environment switch/i)
  assert.match(session, /inference.*entitlement.*missing access record.*created lazily as enabled/is)
  assert.match(session, /self-access.*authentication.*without.*billing entitlement/is)
  assert.match(session, /organization-qualified admin GET.*membership.*authorization.*without.*billing entitlement/is)
  assert.match(session, /explicit disabled record.*unchanged/i)
  assert.match(session, /single global active model.*only runtime model authority/is)
  assert.match(session, /`selectableModels`.*empty/is)
  assert.match(session, /Readiness requires.*current global model policy.*healthy credential.*active model/is)
  assert.match(session, /historical provider mismatches are not readiness failures/is)
  assert.doesNotMatch(session, /ai_access_policy_provider_mismatch/)
  assert.match(session, /unchanged.*local Veslo server.*`\/ai-gateway\/providers/is)
  assert.match(billing, /`GET \/v1\/managed-ai\/entitlement`/)
  assert.match(billing, /managed_ai_entitlement_denied/)
  assert.match(billing, /managed_ai_entitlement_unavailable/)
  assert.match(billing, /self-access.*authentication.*without a billing entitlement check/is)
  assert.match(billing, /inference request.*only after positive DEN entitlement/is)
  assert.match(billing, /organization-qualified admin GET.*active membership.*authorization.*without a billing entitlement check/is)
  assert.match(billing, /one automatic 14-day trial.*registered company domain/is)
  assert.match(billing, /active members inherit.*trial entitlement/is)
  assert.match(billing, /membership changes.*never.*reset.*trial/is)
  assert.match(billing, /immutable.*claim/is)
  assert.match(billing, /manual.*trial.*without.*changing.*expiry/is)
  assert.match(billing, /does not classify public email providers/i)
  assert.match(billing, /verified email.*normalized exact domain/is)

  assert.match(onboarding, /email\/password.*verification.*before.*organization provisioning/is)
  assert.match(onboarding, /active membership.*before.*AI Gateway.*effective assignment/is)
  assert.match(onboarding, /Gateway.*laz(?:y|ily).*enabled.*single global active model.*capability/is)

  assert.match(deployments, /deploy DEN before AI Gateway/i)
  assert.match(deployments, /configure and verify the global model policy/i)
  assert.match(state, /organization id.*runtime memory/is)
  assert.match(state, /must not be persisted.*OpenCode/is)
  assert.match(state, /inference.*entitlement.*missing.*AI-access.*enabled/is)
  assert.match(state, /self-access.*without.*billing entitlement/is)
  assert.match(state, /organization-qualified admin GET.*without.*billing entitlement/is)
  assert.match(state, /explicit disabled.*preserved/i)
  assert.match(state, /user request.*cannot.*switch.*model/is)
  assert.match(state, /historical per-user.*provider.*default_model.*allowed_models_json.*not.*runtime authority/is)
  assert.match(state, /admin.*toggle.*enabled.*technical routing fields.*rejected/is)
  assert.match(appMap, /AI Gateway owns.*global model policy/is)
  assert.match(appMap, /DEN owns.*billing entitlement/is)
  assert.match(appMap, /self-access.*authentication.*inference.*entitlement.*admin.*membership.*authorization/is)
  assert.match(settings, /single global active model.*only managed-AI model/is)
  assert.match(settings, /user.*cannot.*select.*switch.*model/is)
  assert.match(denReadme, /self-access.*no billing check.*inference.*positive DEN entitlement.*admin.*membership.*authorization/is)
  assert.match(denReadme, /single global active model.*exclusive runtime model authority/is)
  assert.match(index, /AI Gateway.*global model policy/i)

  assert.doesNotMatch(canonicalManagedAiDocs, /Den\/AI Gateway remain authoritative for inference/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /managed-AI assignment and admin truth follow the service/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /DEN and standalone AI Gateway show the same access, credential, and model-policy state/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /DEN resolves bindings/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /configured managed-AI service keeps/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /app can read managed-AI access policy from DEN or standalone AI Gateway/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /read-only signup policy resolver are available first/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /Account creation and eligible credential assignment remain available even when the platform model policy/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /default (?:DEN signup bootstrap )?(?:leaves .*resolver )?unwired.*skips? auto(?:matic)?-assignment/is)
  assert.doesNotMatch(canonicalManagedAiDocs, /If no admin policy is assigned, the user can sign in but cannot send prompts/i)
  assert.doesNotMatch(canonicalManagedAiDocs, /Platform admins can .*pick the assigned provider and credential/i)
})
