import {
  CONTENT_LENGTH_HEADER,
  HOP_BY_HOP_REQUEST_HEADERS,
  HOST_HEADER,
  ORIGIN_HEADER,
  VESLO_CLIENT_ID_HEADER,
  VESLO_DEN_ORG_ID_HEADER,
  VESLO_GATEWAY_AUTHORIZATION_HEADER,
  VESLO_GATEWAY_TOKEN_HEADER,
  VESLO_HOST_TOKEN_HEADER,
  VESLO_ORG_ID_HEADER,
  VESLO_SEND_TRACE_ID_HEADER,
  VESLO_WORKSPACE_ID_HEADER,
} from "./request-headers.js";

export const OPENCODE_SESSION_AFFINITY_HEADER = "x-session-affinity";
export const OPENCODE_SESSION_ID_HEADER = "x-session-id";

export const AI_GATEWAY_INTERNAL_REQUEST_HEADERS = [
  VESLO_GATEWAY_AUTHORIZATION_HEADER,
  VESLO_GATEWAY_TOKEN_HEADER,
  VESLO_HOST_TOKEN_HEADER,
  VESLO_CLIENT_ID_HEADER,
  VESLO_WORKSPACE_ID_HEADER,
  VESLO_SEND_TRACE_ID_HEADER,
  VESLO_DEN_ORG_ID_HEADER,
  VESLO_ORG_ID_HEADER,
] as const;

export const AI_GATEWAY_LOCAL_ONLY_REQUEST_HEADERS = [
  OPENCODE_SESSION_AFFINITY_HEADER,
  OPENCODE_SESSION_ID_HEADER,
] as const;

export const AI_GATEWAY_TRANSPORT_REQUEST_HEADERS = [
  ...HOP_BY_HOP_REQUEST_HEADERS,
  HOST_HEADER,
  ORIGIN_HEADER,
  CONTENT_LENGTH_HEADER,
] as const;

export function stripAiGatewayProxyRequestHeaders(headers: Headers): void {
  for (const name of AI_GATEWAY_INTERNAL_REQUEST_HEADERS) {
    headers.delete(name);
  }
  for (const name of AI_GATEWAY_LOCAL_ONLY_REQUEST_HEADERS) {
    headers.delete(name);
  }
  for (const name of AI_GATEWAY_TRANSPORT_REQUEST_HEADERS) {
    headers.delete(name);
  }
}
